version: '3.9'

services:
  mysql:
    image: mysql:8.0    
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    networks:
      - app_network
    volumes:
      - ./sql/migrations:/docker-entrypoint-initdb.d:ro

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_HOST: rabbitmq
    networks:
      - app_network

  application:
    build: "."
    container_name: clean-arch-app
    restart: always
    ports:
      - "8080:8080"
      - "8000:8000"
      - "50051:50051"
    networks:
      - app_network
    depends_on:
      - mysql
      - rabbitmq

networks:
  app_network:
    driver: bridge